### ISSUE TITLE
[Proposal] Allow config dirs

### ISSUE THREAD

**Issue by blaggacao** [acsone/click-odoo#21]
@sbidoul in an attempt to adopt upstream click again, after `ctx` has been added, I have another requirement to make that a possibility:
https://github.com/xoe-labs/click-odoo/commit/d6ba7365827829acfc11354c8c3a114f94ae5bc2

Which is needed because of https://github.com/xoe-labs/odoo-dev/commit/baba813670f1b67f0365ce35f57c3c80569d6630 being part of the infrastructure stack I accoustom to use.

Would that be a possibility to accept taking config directories?

**Comment by blaggacao** [comment]
On the long run I'm still betting on that this would be officially supported by Odoo one day. It would be a good thing. But if there is no resolve, I sure could do as you suggest. I'd have to postpone it though ;-)

**Comment by blaggacao** [comment]
@sbidoul Btw, wouldn't a helping word from Acsone on upstream be worth the effort?

**Comment by blaggacao** [comment]
Here is the link: https://github.com/odoo/odoo/pull/28002

**Comment by sbidoul** [comment]
At Acsone we are not suffering from that. We are mostly happy with OCA/server-env and the current odoo config.
