### ISSUE TITLE
click-odoo-initdb question

### ISSUE THREAD

**Issue by gridworkz** [acsone/click-odoo#29]
Hello: I've created a few template dbs in Odoo and I would like to get an example of using click-odoo-initdb to create a new database from one of these templates. If you have a working example syntax of it that would be great. I'm just a little confused on how to create/access the cache of template dbs.

**Comment by sbidoul** [comment]
@gridworkz can you move your question to https://github.com/acsone/click-odoo-contrib, I'll answer it there.

**Comment by gridworkz** [comment]
Thnx
