### ISSUE TITLE
Pass --addons-path to click-odoo

### ISSUE THREAD

**Issue by voronind** [acsone/click-odoo#30]
AFAIU we cannot use --addons-path option. Why?
"-c config" is not handful.

**Comment by sbidoul** [comment]
[AFAICS](https://github.com/acsone/click-odoo#command-line-interface-click-odoo) in the documentation, you can :)

Can you retry with the latest version and if the problem persist provide more details about the issue?

**Comment by sbidoul** [comment]
Closing as no answer. Feel free to reopen if needed.
