### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by sbidoul** [acsone/click-odoo#4]
* there is a info log line being emitted when the database connections are closed even if log level > info
* setting --log-level=debug applies to odoo logs only but not logging performed by the script

**Comment by blaggacao** [comment]
Would it be acceptable to incorporate a json log formatter? I could take this one in combo. 
JSON formatted logs are easier to deal with by log forwarders as they don't require buffering for multi line logs which is a PITA at the moment.

**Comment by sbidoul** [comment]
Json logging is another issue than this one. As this is would be of interest for any Odoo instance (not just click-odoo scripts) this should be done outside of click-odoo. For example: https://github.com/OCA/server-tools/tree/8.0/logging_json

**Comment by blaggacao** [comment]
If something like: https://github.com/odoo/odoo/pull/23417 would get accepted, whoulc this require adoptions within `click-odoo`? or would it just be magically taken?

Best (shared) course of action (in my opinion):

- Lobby for upstream json logging
- I'll take this #4, if you're ok with it.

**Comment by Yajo** [comment]
This should be reopened after https://github.com/acsone/click-odoo/commit/8c2234c3a57b8016da0c516f907cf91c32469993

**Comment by Yajo** [comment]
One idea:

```
click-odoo-update --log-handler click_odoo_contrib.update:DEBUG
```

Just as Odoo 8+ lets you do: https://www.odoo.com/documentation/8.0/reference/cmdline.html#logging

**Comment by sbidoul** [comment]
@Yajo I created #27 for the first part.

The other part I'm not sure something has to / can / needs to be done.

Log handlers in the config file are supported. We could add a CLI option but I'm not sure it's really useful.

**Comment by Yajo** [comment]
> I'm not sure it's really useful

I'd use it, for sure.

Setting DEBUG level is something I do only when developing, and adding a flag to the command is the shortest path to get the job done. Besides, it matches what Odoo has, so it probably wouldn't need to do anything else than just passing those flags to the underlying odoo command, and it'd take care of configuring the handlers.
