### ISSUE TITLE
[Question] how to make linting tools ignore the warning that `env` is not defined

### ISSUE THREAD

**Issue by obayit** [acsone/click-odoo#42]
In the example in the `README` file you have this:
```
#!/usr/bin/env python
from __future__ import print_function

for u in env['res.users'].search([]):
    print(u.login, u.name)
```

In my `vs code` it shows warning that `env` is not defined, is there a way to make that warning disappear? The closes thing I could find was the key word `global` but I don't thing it is usable here.

My question: how to make this warning disappear?

**Comment by sbidoul** [comment]
You could add `env = env  # noqa` at the beginning of the file.
Or use the more elaborate method, using `@click_odoo.env_options()`.
