### ISSUE TITLE
Pass server_wide_modules without using custom config

### ISSUE THREAD

**Issue by pedrobaeza** [acsone/click-odoo#50]
Is it possible to specify `server_wide_modules` without creating a custom config file and passing such file with the option? This is very needed for OpenUpgrade post-migration operations in 14.0+.

**Comment by sbidoul** [comment]
Can you elaborate the use case ?
Click-odoo does not start a server, so this option does not make much sense as it would not be used anywhere.

**Comment by pedrobaeza** [comment]
I need it for passing `openupgrade_framework` module as server wide module for patching the function that deletes records for not failing if the model doesn't exist when uninstalling modules using click-odoo-uninstall. I'm out of the office now for pointing specific lines, but I can do it later if you want.

**Comment by sbidoul** [comment]
maybe you can `import odoo.addons.openupgrade_framework` in your script ?

**Comment by pedrobaeza** [comment]
That's the question. I'm not developing any script, but using this one: https://github.com/acsone/click-odoo-contrib/blob/master/click_odoo_contrib/uninstall.py

It's used for uninstalling modules after the migration process for useless/discarded modules, but it may fail due to this Odoo line:

https://github.com/odoo/odoo/blob/290517b3a7d21fb99d84a95c422ed163e88c96aa/odoo/addons/base/models/ir_model.py#L2174

if the model doesn't exist anymore.

This is patched in `openupgrade_framework` in:

https://github.com/OCA/OpenUpgrade/blob/a31e80324cfecd18bf51f48877d5a88422bc987e/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_model.py#L55
https://github.com/OCA/OpenUpgrade/blob/a31e80324cfecd18bf51f48877d5a88422bc987e/openupgrade_framework/odoo_patch/odoo/api.py#L32

so the idea is to pass the module as server_wide_module to this script for that, but not having to recreate a full config file. For other configurations like DB name, PGHOST, etc, we have other alternatives, but not for server wide modules.

**Comment by sbidoul** [comment]
I still think this option does not make much sense in click-odoo. The uninstall script is very small, maybe you can simply adapt it and include it in the openupgrade project.

**Comment by pedrobaeza** [comment]
OK, I will find another way, thanks.
