### ISSUE TITLE
Improve UX with hook for subcommands

### ISSUE THREAD

**Issue by blaggacao** [acsone/click-odoo#7]
- Second order libraries like, `click-odoo-migrator` axpose their own entry point
- It would be nice if `click-odoo` provided a hook to register second order modules as subcommands so that `click-odoo-migrator` would become `click-odoo migrator`.

**Comment by sbidoul** [comment]
I don't see the point. click-odoo makes it easy to create your own commands (as you have seen  examples in click-odoo-contrib). What would be the benefit of having subcommands to click-odoo?

**Comment by ovnicraft** [comment]
I see the point to use click-odoo as tool for managing.
IDK if its a good example:

`pip install click-odoo[migrator]`

so then i an run modules and my own commands.

Looks good to extend library.

**Comment by blaggacao** [comment]
I agree, it's mostly cosmetics, and I'm not even sure it can be done properly, but if so, it is nice cosmetics. Users can "craft" their own `click-odoo` command as they need.

I would immediately port `-loader`, `-initializer` (yours) and `-migrator` to such.

**Comment by blaggacao** [comment]
There is another point, equally important:
It will create an organizing momentum and will surface discussion among the community on scope and focused of any given subcommand.

**Comment by sbidoul** [comment]
Not sure I understand what you mean and I don't see how to do implement it anyway. PR welcome.

In the meantime, I'm happy to add pointers to projects using click-odoo in the README: that should help building the ecosystem.

**Comment by blaggacao** [comment]
I'm also not sure, how to implement that, if I come across a solution, I'll do a PR. For the meantime, collecting them in the readme, would be greate: so here it goes:
- https://github.com/xoe-labs/click-odoo-migrator
- https://github.com/xoe-labs/click-odoo-initializer (outfactored from your contrib)
- https://github.com/xoe-labs/click-odoo-loader

Planned some day: `click-odoo-tester` & `click-odoo-translator`

**Comment by blaggacao** [comment]
@sbidoul The ultimate answer: https://github.com/click-contrib/click-plugins#why

**Comment by sbidoul** [comment]
click-odoo is not meant nor designed to be extended with plugins, it is a library to build your own scripts (using `@click_odoo.env_options`, which is a one-liner).
